name: Build and Run

on:
  pull_request:
    types: [opened, reopened, synchronize]
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    if: startsWith(github.head_ref, 'pr-add-ci-') || startsWith(github.head_ref, 'pr-add-dwc2-')

    strategy:
      matrix: 
        zephyr_cont_ver: [ "latest" ]

    runs-on: ubuntu-latest
    container:
      image: zephyrprojectrtos/ci:${{ matrix.zephyr_cont_ver }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Configure Python requirements
        shell: bash
        run: |
          python3 -m venv .venv
          . .venv/bin/activate
          pip install -U pip wheel
          pip install -r scripts/requirements.txt -r scripts/requirements-build-test.txt

      - name: West init/update
        shell: bash
        run: |
          . .venv/bin/activate
          # might be skipped as your repo is already a full zephyr workspace
          west --version
          west update

      - name: Build (Produce twister-out)
        shell: bash
        env:
          PYTEST_DISABLE_PLUGIN_AUTOLOAD: "1" # TODO: workaround harness double registration?
        run: |
          . .venv/bin/activate
          west twister \
            -T samples/subsys/testsuite/pytest/shell \
            -p esp32s3_devkitc/esp32s3/procpu \
            -s sample.pytest.shell \
            --build-only \
            -j 1 -v --outdir twister-out

      - name: Pack twister-out artifact
        shell: bash
        run: |
          tar -czf twister-out.tgz twister-out

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: twister-out
          path: twister-out.tgz
          if-no-files-found: error

  run:
    if: startsWith(github.head_ref, 'pr-add-ci-') || startsWith(github.head_ref, 'pr-add-dwc2-')
    runs-on: [ self-hosted, esp32s3 ]
    needs: [ build ]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download twister-out artifact
        uses: actions/download-artifact@v4
        with:
          name: twister-out

      - name: Unpack twister-out
        shell: bash
        run: |
          rm -rf twister-out
          tar -xzf twister-out.tgz

      - name: Python venv + requirements (clean)
        shell: bash
        run: |
          python3 -m venv .venv
          . .venv/bin/activate
          pip install -U pip wheel
          pip install -r scripts/requirements.txt -r scripts/requirements-build-test.txt

      - name: Run on hardware
        shell: bash
        env:
          PYTEST_DISABLE_PLUGIN_AUTOLOAD: "1"
        run: |
          . .venv/bin/activate

          # Important: --test-only reuses builds in twister-out from previous job.
          # --device-testing + --hardware-map selects your DUT and flashes/runs it.
          west twister \
            -T samples/subsys/testsuite/pytest/shell \
            -p esp32s3_devkitc/esp32s3/procpu \
            -s sample.pytest.shell \
            --test-only \
            --device-testing \
            --hardware-map tests/hil/hw/esp32s3/map-esp32s3.yml \
            -j 1 -v --outdir twister-out

      - name: Upload Twister reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: twister-reports
          path: |
            twister-out/twister.xml
            twister-out/twister_report.xml
            twister-out/twister.json